### ISSUE TITLE
0.4.0 incompatible with Pytest 6.2.2

### ISSUE THREAD

**Issue by martinhoyer** [dcermak/pytest_container#202]
Hi,

looks like the new release is not working on older pytest versions, like 6.2.2, included in CentOS Stream 9:

```
File "/tmp/tmp.rXUKuNZN61/lib64/python3.9/site-packages/pytest_container/container.py", line 900, in <module>
    Union[Collection[pytest.MarkDecorator], pytest.MarkDecorator]
AttributeError: module 'pytest' has no attribute 'MarkDecorator'
```

Shouldn't the required pytest version be increased in the project's metadata?
